export default function Weekly() {
    return(
        <div className="weekly-container w-[98%] h-full absolute left-1/2 -translate-x-1/2">
            <div className="days-name-container bg-amber-100 fixed w-full h-20"></div>
            <div className="hours-name-container bg-amber-600 absolute h-full w-20"></div>
            <div className="task-display-container bg-amber-800 absolute h-[calc(100%-5rem)] w-[calc(100%-5rem)] left-20 top-20 overflow-hidden">
                <div className="task-display bg-amber-950 grid grid-cols-7 [grid-template-rows:repeat(24,_8rem)] gap-0 h-full w-[100%] overflow-y-auto">
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                    <div className="task-container col-span-1 row-span-1 border-r-1 border-b-1"></div>
                </div>
            </div>
        </div>
    );;
}

/*
TODO:
    - Google calendar view
    - Be sure task rendered at right place
    - Scrollable 24 hours.
    - Adjust the current hour in the middle of the container by using useRef.
    - Highlight the current hour and day. make the intersection darker.
*/